version: "3.1"
services:
  # db
  postgres:
    ports:
      - 5432:5432
      
  # zt container
  zerotier:
    image: zyclonite/zerotier:1.12.1

  # ztnet
  ztnet:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    environment:
      ZTNET_TRUST_HOST: "true"
    working_dir: /workspaces
    volumes:
      - .:/workspaces:cached
    networks:
      - app-network
    depends_on:
      - postgres
      - zerotier
